// ███████████ █████                                                █████   █████                      ████   █████   
//░█░░░███░░░█░░███                                                ░░███   ░░███                      ░░███  ░░███    
//░   ░███  ░  ░███████    ██████   ████████    ███████  ██████     ░███    ░███   ██████   █████ ████ ░███  ███████  
//    ░███     ░███░░███  ░░░░░███ ░░███░░███  ███░░███ ███░░███    ░███    ░███  ░░░░░███ ░░███ ░███  ░███ ░░░███░   
//    ░███     ░███ ░███   ███████  ░███ ░███ ░███ ░███░███████     ░░███   ███    ███████  ░███ ░███  ░███   ░███    
//    ░███     ░███ ░███  ███░░███  ░███ ░███ ░███ ░███░███░░░       ░░░█████░    ███░░███  ░███ ░███  ░███   ░███ ███
//    █████    ████ █████░░████████ ████ █████░░███████░░██████        ░░███     ░░████████ ░░████████ █████  ░░█████ 
//   ░░░░░    ░░░░ ░░░░░  ░░░░░░░░ ░░░░ ░░░░░  ░░░░░███ ░░░░░░          ░░░       ░░░░░░░░   ░░░░░░░░ ░░░░░    ░░░░░  
//                                             ███ ░███                                                               
// © 2021                                     ░░██████                                                                
// @ govindthange                              ░░░░░░                                                                 

//
// @version=5
// @description is a collection of utility functions required by Woodwind Playbook.
//
library("ThangeVault", overlay=true)


//
// @function shows text on the bar
// @param msg, message to be shown on the label
//
export tag(string msg) =>
    label lbl = label.new(bar_index, na, msg, xloc.bar_index, yloc.price, color(na), label.style_none, color.white, size.small, text.align_left)
    label.set_xy(lbl, bar_index, ta.highest(10)[1])
    label.set_text(lbl, msg)


// 
// @function creates a string template to restrict price precision to ticks.
// @returns a string format template
//
export tickFormat() =>
    s = str.tostring(syminfo.mintick)
    s := str.replace_all(s, "25", "00")
    s := str.replace_all(s, "5",  "0")
    s := str.replace_all(s, "1",  "0")

