// ███████████ █████                                                █████   █████                      ████   █████   
//░█░░░███░░░█░░███                                                ░░███   ░░███                      ░░███  ░░███    
//░   ░███  ░  ░███████    ██████   ████████    ███████  ██████     ░███    ░███   ██████   █████ ████ ░███  ███████  
//    ░███     ░███░░███  ░░░░░███ ░░███░░███  ███░░███ ███░░███    ░███    ░███  ░░░░░███ ░░███ ░███  ░███ ░░░███░   
//    ░███     ░███ ░███   ███████  ░███ ░███ ░███ ░███░███████     ░░███   ███    ███████  ░███ ░███  ░███   ░███    
//    ░███     ░███ ░███  ███░░███  ░███ ░███ ░███ ░███░███░░░       ░░░█████░    ███░░███  ░███ ░███  ░███   ░███ ███
//    █████    ████ █████░░████████ ████ █████░░███████░░██████        ░░███     ░░████████ ░░████████ █████  ░░█████ 
//   ░░░░░    ░░░░ ░░░░░  ░░░░░░░░ ░░░░ ░░░░░  ░░░░░███ ░░░░░░          ░░░       ░░░░░░░░   ░░░░░░░░ ░░░░░    ░░░░░  
//                                             ███ ░███                                                               
// © 2021                                     ░░██████                                                                
// @ govindthange                              ░░░░░░                                                                 

// @version=5

// @description Thange Vault is a collection of utility functions required by the Thange Woodwind Playbook.
library("ThangeVault")

// @function Print debug information
// @param msg message to be logged on console
// @returns nothing
export debug(string msg) =>
	label lbl = label.new(bar_index, na, msg, xloc.bar_index, yloc.price, color(na), label.style_none, color.white, size.small, text.align_left)
    label.set_xy(lbl, bar_index, ta.highest(10)[1])
    label.set_text(lbl, msg)

// 
// @function Create a string template to restrict stop-loss, take-profit level precision to ticks.
// @returns A string format template 
export tickFormat() =>
    s = str.tostring(syminfo.mintick)
    s := str.replace_all(s, "25", "00")
    s := str.replace_all(s, "5",  "0")
    s := str.replace_all(s, "1",  "0")
